#.travis.yml

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli@1.3.2

script:
  - ng build --prod

after_success:
#  - firebase deploy --token $FIREBASE_TOKEN

notifications:
#  email:
#    on_failure: change
#    on_success: change
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
   branch: gh-pages
